Fix #119 issue with semicolon inside string (expression)
mark-wiemer/vscode-autohotkey-plus-plus pull request #159
Opened 2022-07-16 19:04 UTC by kyklish

Closes #119.

Changes proposed in this pull request:

-   change order of .replace() regexp

Notifying @mark-wiemer

2022-07-16 19:43 UTC, mark-wiemer commented
Should we maybe move the "replace semicolon" to the very end of the chain? I'm concerned with this case:

```ahk
MsgBox, { ; comment with close brace }
```

2022-07-16 19:44 UTC, mark-wiemer commented
I'll check this out tomorrow when I have some time 🙂

2022-07-16 19:57 UTC, kyklish commented
> Should we maybe move the "replace semicolon" to the very end of the chain? I'm concerned with this case:
> 
> ```ahk
> MsgBox, { ; comment with close brace }
> ```

You right. Moved to very end of chain.

2022-07-17 05:43 UTC, kyklish commented
purify() may return single space character, so additionally trim purified line to make it empty (I need this for future formatter fixes).

2022-07-18 04:39 UTC, mark-wiemer requested changes

2022-07-18 04:39 UTC, mark-wiemer commented on src/common/codeUtil.ts
> +            .replace(/\b(msgbox)\b.+?%/gi, '$1')
Let's add some unit tests for `purify` so we know what exactly we fixed and we don't break it in the future :)

2022-07-18 19:50 UTC, mark-wiemer commented
Yes, this is awesome! I'll have a bit of feedback once my workday is done, but I think we will be able to merge this as-is!! Thank you so much, you are very good at this :)

2022-07-18 20:08 UTC, mark-wiemer commented
Can you provide a larger snippet? And maybe a screenshot of your editor? I think there is something simple we are missing. Have you tried the playground at TypeScriptlang.org?
________________________________
From: Kyklish ***@***.***>
Sent: Monday, July 18, 2022 1:02:31 PM
To: mark-wiemer/vscode-autohotkey-plus-plus ***@***.***>
Cc: Mark Wiemer ***@***.***>; Mention ***@***.***>
Subject: Re: [mark-wiemer/vscode-autohotkey-plus-plus] Fix #119 issue with semicolon inside string (expression) (PR #159)


Yes, but it's produce error: let var = '';, or explicit type like string. Tooltip says can't find variable with let name. I will investigate that tomorrow.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmark-wiemer%2Fvscode-autohotkey-plus-plus%2Fpull%2F159%23issuecomment-1188237852&data=05%7C01%7C%7C46d0479b991e4283339208da68f87356%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637937713534148668%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5RSyw3%2BN0LJYvNL%2Fz3K2SMgf0y%2BQp5WriTtwJItEbyQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB3YOEA3RE744ECFOR4XK2TVUWZ5PANCNFSM53YQASVA&data=05%7C01%7C%7C46d0479b991e4283339208da68f87356%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637937713534148668%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vl0zd55bpyhe90NTTWRuJlb11Pv6ce0416lEymvrG70%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-07-18 20:16 UTC, kyklish commented
Yep, thanks.

2022-07-19 16:39 UTC, kyklish commented
Every bugfix in formatter don't pass formatter's test with file `ahk-explorer.ahk`. How to deal with this file?

I can add #160 bugfix in this PR to produce more-less relevant format result for `ahk-explorer.ahk` and commit it in this PR.

2022-07-19 17:55 UTC, mark-wiemer commented
Update ahk-explorer.out.ahk so the test passed, then I will look at the difference and make sure we didn't introduce any bad formatting behaviors.

Same applies to any failing formatting test :)
________________________________
From: Kyklish ***@***.***>
Sent: Tuesday, July 19, 2022 9:40:05 AM
To: mark-wiemer/vscode-autohotkey-plus-plus ***@***.***>
Cc: Mark Wiemer ***@***.***>; Mention ***@***.***>
Subject: Re: [mark-wiemer/vscode-autohotkey-plus-plus] Fix #119 issue with semicolon inside string (expression) (PR #159)


Every bugfix in formatter don't pass formatter's test with file ahk-explorer.ahk. How to deal with this file?

I can add #160<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmark-wiemer%2Fvscode-autohotkey-plus-plus%2Fpull%2F160&data=05%7C01%7C%7Cebf8e545fcbe4827f84808da69a5562a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637938456073650466%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Jub%2BQxNLZg%2FoA%2BeSiiIExrWjZcinps8VhGHRFOzsLz8%3D&reserved=0> bugfix in this PR to produce more-less relevant format result for ahk-explorer.ahk and commit it in this PR.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmark-wiemer%2Fvscode-autohotkey-plus-plus%2Fpull%2F159%23issuecomment-1189316897&data=05%7C01%7C%7Cebf8e545fcbe4827f84808da69a5562a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637938456073650466%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0AByMs0yz87hZiNBvsNwYzO2mtMWx88JZqQ80M1CxGM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB3YOEC5YLBAP2TPTNRFMXLVU3K6LANCNFSM53YQASVA&data=05%7C01%7C%7Cebf8e545fcbe4827f84808da69a5562a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637938456073650466%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=doj%2BLt2Adh%2B%2BD96aebGTt03C%2FgTwcRuMCznEU82vGpg%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-07-19 18:40 UTC, kyklish commented
I run `npm run eslint_inner` and got this (no errors):

`vscode-autohotkey-plus-plus@2.8.3 eslint_inner
eslint --ext ts --max-warnings=0`

2022-07-20 03:18 UTC, mark-wiemer commented
> I can't commit updated `ahk-explorer.out.ahk` :( `npm run validate` in VS Code done without errors When I try commit I got this error:
> 
> ```
> npm run eslint_inner
> [FAILED]F:\GAMES\Android\VS Code\vscode-autohotkey-plus-plus\src\test\suite\format\samples\ahk-explorer.out.ahk
> 
> ■ npm run tsc
>       ↓1:2 package.json   — no fileserror [SKIPPED]  Parsing error: Unknown keyword or identifier. Did you mean 'from'?
> ```

Thanks for the headsup, let me rectify this :)

2022-07-20 03:25 UTC, mark-wiemer commented
@kyklish, see cc7c153

```jsonc
// package.json
    "lint-staged": {
        "*": "prettier --check",
        "src/**/*.ts": [
```

2022-07-20 03:31 UTC, mark-wiemer commented
I've also updated the formatting tests in my branch, https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/tree/fix-formatter-bug

2022-07-31 05:35 UTC, mark-wiemer approved these changes
Fantastic work once again :)

2022-07-31 18:02 UTC, mark-wiemer submitted a review, later dismissed

2022-07-31 18:10 UTC, mark-wiemer commented
Can't merge until we're passing the tests. I think the regex rearrangements are responsible here. We should be preserving quoted strings, not trimming them or removing extra spaces.

2022-07-31 18:26 UTC, kyklish commented
Yes. Now semicolon inside quoted string became single line comment. I'm thinking about proper regex for comment detection.

2022-08-13 17:57 UTC, mark-wiemer approved these changes

2022-08-13 17:58 UTC, merged