fix #56 issue with wrong Return statement indent
mark-wiemer/vscode-autohotkey-plus-plus pull request #160
Opened 2022-07-16 19:29 UTC by kyklish

Closes #56.

Changes proposed in this pull request:

-   fix typo comparison '===' to assignment '='

Notifying @mark-wiemer

2022-07-16 19:33 UTC, kyklish commented
This test file fully wrong :( `.\vscode-autohotkey-plus-plus\src\test\suite\format\samples\ahk-explorer.out.ahk`
After this fix, test fails.

2022-07-16 19:39 UTC, mark-wiemer commented
No worries about the failing tests, this looks great! I will triple check the failing test, write a new test that would've failed without the change, and make sure everything is good 😊

Unfortunately I'm away from my computer right now, but I'll check out these pull requests tomorrow at the latest.

2022-07-16 20:00 UTC, kyklish commented
Don't hurry up with new test file. Fixing #161 issue (if I succeed) will again broke it.

2022-07-18 04:37 UTC, mark-wiemer requested changes

2022-07-18 04:37 UTC, mark-wiemer commented on src/providers/formattingProvider.ts
> +                tagDepth = 0;
As always, let's update tests in this PR itself :)

2022-07-21 17:42 UTC, kyklish commented
Will be fixed in #159.

2022-07-21 18:18 UTC, closed without merging