Add option to extension's settings: "Formatter: Trim extra spaces between words"
mark-wiemer/vscode-autohotkey-plus-plus pull request #191
Opened 2022-07-22 17:32 UTC by kyklish

Closes #187.

Changes proposed in this pull request:

-   make trimming extra spaces between words optional

---

Notifying @mark-wiemer

2022-07-31 06:03 UTC, mark-wiemer requested changes
Almost ready to merge!

2022-07-31 06:03 UTC, mark-wiemer commented on src/test/suite/providers/formatting/formattingProvider.utils.test.ts
> +            },
```suggestion
            },
            {
                in: 'MsgBox,  4,   , testing   testing',
                rs: 'MsgBox, 4, , testing testing',
                ts: true,
            },
```

2022-07-31 06:03 UTC, mark-wiemer commented on src/test/suite/providers/formatting/formattingProvider.utils.test.ts
> +            },
Just want to test something other than assignment here

2022-07-31 11:20 UTC, kyklish commented on src/providers/formattingProvider.utils.ts
> +        ? line.replace(/ {2,}/g, ' ') // Remove extra spaces between words
I got this bug (formatter modify quoted string and continuation sections) in my TODO list. It's not easy to fix it here, separate PR needed.

2022-07-31 11:28 UTC, kyklish commented on src/providers/formattingProvider.utils.ts
> +        ? line.replace(/ {2,}/g, ' ') // Remove extra spaces between words
Created #199.

2022-08-13 18:30 UTC, mark-wiemer commented on src/providers/formattingProvider.utils.ts
> +        ? line.replace(/ {2,}/g, ' ') // Remove extra spaces between words
Awesome, resolving this one.

2022-08-13 18:31 UTC, mark-wiemer approved these changes

2022-08-13 18:31 UTC, mark-wiemer commented
Let's resolve merge conflicts and then we're good to go, @kyklish :)

2022-08-14 10:21 UTC, kyklish commented
> Let's resolve merge conflicts and then we're good to go, @kyklish :)

Done.

2022-08-14 20:41 UTC, merged