Refactor: assign settings in groups
mark-wiemer/vscode-autohotkey-plus-plus pull request #196
Opened 2022-07-24 07:55 UTC by kyklish

Closes #ISSUE.

Changes proposed in this pull request:

-   assign settings in groups (for my new options, that are already in group 'formatter')
-   sort settings and `enum ConfigKey` in alphabet order

Notifying @mark-wiemer

2022-07-31 05:57 UTC, mark-wiemer requested changes

2022-07-31 05:57 UTC, mark-wiemer commented on package.json
> +                "ahk++.ui.showDebugButton": {
VS Code automatically renders `ui` as `Ui` which I think looks really gross. Let's just show `Menu` for now. See [Extension API - configuration](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration). I thought there was an issue for this in VS Code, but I've lost it.

```suggestion
                "ahk++.menu.showDebugButton": {
```

2022-07-31 05:57 UTC, mark-wiemer commented on package.json
> +                    "when": "editorLangId == ahk && config.ahk++.ui.showDebugButton",
```suggestion
                    "when": "editorLangId == ahk && config.ahk++.menu.showDebugButton",
```

2022-07-31 10:32 UTC, kyklish commented
Do I need re-request review after I made changes?

2022-08-13 18:00 UTC, mark-wiemer approved these changes

2022-08-13 18:00 UTC, mark-wiemer commented
> Do I need re-request review after I apply suggestions from code review?

No, I will actively monitor changes to PRs. This month I've been a bit busy, but I'm finally getting back to work today :)

2022-08-13 18:02 UTC, merged